### ISSUE TITLE
Error trying to import deriv-api 

### ISSUE THREAD

**Issue by guilhermelionzo** [binary-com/deriv-api#21]
Hi there,

I'm trying to import deriv-api, but I'm receving the following error message:
```
const express = require('express');
                ^

**ReferenceError: require is not defined**
    at file:///C:/Users/User/vscode-workspace/binaryboot/index.js:1:17
    at ModuleJob.run (internal/modules/esm/module_job.js:110:37)
    at async Loader.import (internal/modules/esm/loader.js:179:24)
error Command failed with exit code 1.
```
I ran the code below using NodeJs v14.0.0 and v13.5.

Could you guys help me?
```
const express = require('express');
const cors = require('cors');
const DerivAPI = require('@deriv/deriv-api');

const api = new DerivAPI({app_id: 'MY_API_ID' });

const app = express();

app.use(cors());

app.use(express.json());

app.listen(3333,()=>{
    console.log('debug > console listening on port 3333');
});
```

If you guys need more information, please, let me know.

**Comment by BrunoEmerich** [comment]
Hello my friend!!! 

This error may occur because the `require()` isnt defined for the client-side!! Try to use the `import {variables} from "YourModule"` instead to see if it works.

Another option is put as top level of your `package.json` the type resolution as module:

`{ "type": "module" }`

The `import` statement if the default module resolution on ECMAScript 6.

I hope this solve your problem.

**Comment by guilhermelionzo** [comment]
> Hello my friend!!!
> 
> This error may occur because the `require()` isnt defined for the client-side!! Try to use the `import {variables} from "YourModule"` instead to see if it works.
> 
> Another option is put as top level of your `package.json` the type resolution as module:
> 
> `{ "type": "module" }`
> 
> The `import` statement if the default module resolution on ECMAScript 6.
> 
> I hope this solve your problem.

Hi @BrunoEmerich ,

Thank you for your reply my friend 😄 

I've made a mistake and sent the wrong error message and code. I just updated the issue description. 

My **`package.json`** have `{ "type": "module" }` and all the external modules/libs are imported using `import {variables} from "YourModule"`.

Unfortunately the error:
**`The requested module '@deriv/deriv-api' does not provide an export named 'default'`**

Probably I'm doing something wrong.

**Comment by salar-fs** [comment]
@guilhermelionzo Is the issue resolved?
